// Package parser contains code generated by Antlr based from the Lexer.g4 and Parser.g4 files,
// using the generateParser.sh file at the root of the git repository of the ysgo module.
// Only the indent_aware_lexer.go file has been manually written - other Go files shouldn't be
// modified.
package parser
