name: on-push
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Generate lexer/parser files with antlr
        run: ./generateParser.sh
      - name: Display potential updates
        run: git diff
      - name: Make sure lexer/parser files were already up-to-date
        run: git diff-index --quiet HEAD
      - name: Run go vet
        run: go list ./... | grep -v parser | xargs go vet
      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.4.6
          staticcheck ./...
      - name: Test
        run: go test -coverprofile='coverage.txt' -covermode=atomic ./...
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
