name: on-push
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Generate lexer/parser files with antlr
        run: ./generateParser.sh
      - name: Display potential updates
        run: git diff
      - name: Make sure lexer/parser files were already up-to-date
        run: git diff-index --quiet HEAD
      - name: Test
        run: go test -coverprofile='coverage.txt' -covermode=atomic ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
